//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatDetector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int BD_DETECTION_RANGES {
            get {
                return ((int)(this["BD_DETECTION_RANGES"]));
            }
            set {
                this["BD_DETECTION_RANGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float BD_DETECTION_RATE {
            get {
                return ((float)(this["BD_DETECTION_RATE"]));
            }
            set {
                this["BD_DETECTION_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.915")]
        public float BD_DETECTION_FACTOR {
            get {
                return ((float)(this["BD_DETECTION_FACTOR"]));
            }
            set {
                this["BD_DETECTION_FACTOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float BD_QUALITY_DECAY {
            get {
                return ((float)(this["BD_QUALITY_DECAY"]));
            }
            set {
                this["BD_QUALITY_DECAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.96")]
        public float BD_QUALITY_TOLERANCE {
            get {
                return ((float)(this["BD_QUALITY_TOLERANCE"]));
            }
            set {
                this["BD_QUALITY_TOLERANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float BD_QUALITY_REWARD {
            get {
                return ((float)(this["BD_QUALITY_REWARD"]));
            }
            set {
                this["BD_QUALITY_REWARD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float BD_QUALITY_STEP {
            get {
                return ((float)(this["BD_QUALITY_STEP"]));
            }
            set {
                this["BD_QUALITY_STEP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int BD_MINIMUM_CONTRIBUTIONS {
            get {
                return ((int)(this["BD_MINIMUM_CONTRIBUTIONS"]));
            }
            set {
                this["BD_MINIMUM_CONTRIBUTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public float BD_FINISH_LINE {
            get {
                return ((float)(this["BD_FINISH_LINE"]));
            }
            set {
                this["BD_FINISH_LINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfFloat xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <float>0.001</float>
  <float>0.005</float>
  <float>0.01</float>
  <float>0.02</float>
  <float>0.04</float>
  <float>0.08</float>
  <float>0.1</float>
  <float>0.15</float>
  <float>0.3</float>
</ArrayOfFloat>")]
        public float[] BD_REWARD_TOLERANCES {
            get {
                return ((float[])(this["BD_REWARD_TOLERANCES"]));
            }
            set {
                this["BD_REWARD_TOLERANCES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfFloat xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <float>20</float>
  <float>10</float>
  <float>8</float>
  <float>1</float>
  <float>0.5</float>
  <float>0.25</float>
  <float>0.125</float>
  <float>0.0625</float>
  <float>0.03125</float>
</ArrayOfFloat>")]
        public float[] BD_REWARD_MULTIPLIERS {
            get {
                return ((float[])(this["BD_REWARD_MULTIPLIERS"]));
            }
            set {
                this["BD_REWARD_MULTIPLIERS"] = value;
            }
        }
    }
}
